authors:
  - barb@hooli.com

description: >
  A List-component displays items in an ordered or unordered list.

tags:
  - Progress/Draft
  - Release/0.6

custom:
  synonyms:
    - Listing
    - Index
  
version: 1
